// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net_message.proto

package com.dylanlaufenberg.portlandstate.cs300.proto;

public final class NetMessage {
  private NetMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dylanlaufenberg.cs300.proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
     */
    com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType getMessageType();

    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    boolean hasCredentialData();
    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getCredentialData();
    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder getCredentialDataOrBuilder();

    /**
     * <code>string sender = 3;</code>
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 3;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string recipient = 4;</code>
     */
    java.lang.String getRecipient();
    /**
     * <code>string recipient = 4;</code>
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <code>string message = 5;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * A valid NetMessage consists of a message_type field and possibly one, corresponding sub-message as indicated
   * in the MessageType definition comments. If a sub-message is required, it should be populated as indicated
   * in the definition for that message type.
   * Because of the compatibility limitations on required fields, the required keyword is not used. Instead,
   * requirements are expected to be enforced by the applications on either end. It is expected that any extra
   * data sent (e.g. a PrivateMessage with message_type = 0) will be ignored and, most likely, not even detected.
   * </pre>
   *
   * Protobuf type {@code dylanlaufenberg.cs300.proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dylanlaufenberg.cs300.proto.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      messageType_ = 0;
      sender_ = "";
      recipient_ = "";
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 18: {
              com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder subBuilder = null;
              if (credentialData_ != null) {
                subBuilder = credentialData_.toBuilder();
              }
              credentialData_ = input.readMessage(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(credentialData_);
                credentialData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              recipient_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.class, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code dylanlaufenberg.cs300.proto.Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * DO NOT USE. Must start at 0, but 0 seems to get lost somewhere along the way. Bug in Protobuf?
       * </pre>
       *
       * <code>FAKE = 0;</code>
       */
      FAKE(0),
      /**
       * <pre>
       * Requires Credentials message
       * </pre>
       *
       * <code>REGISTER = 1;</code>
       */
      REGISTER(1),
      /**
       * <pre>
       * Requires Credentials message
       * </pre>
       *
       * <code>LOGIN = 2;</code>
       */
      LOGIN(2),
      /**
       * <pre>
       * No associated message
       * </pre>
       *
       * <code>LOGOUT = 3;</code>
       */
      LOGOUT(3),
      /**
       * <pre>
       * No associated message
       * </pre>
       *
       * <code>DELETE_ACCOUNT = 4;</code>
       */
      DELETE_ACCOUNT(4),
      /**
       * <pre>
       * Requires PublicMessage
       * </pre>
       *
       * <code>PUBLIC_MESSAGE = 5;</code>
       */
      PUBLIC_MESSAGE(5),
      /**
       * <pre>
       * Requires PrivateMessage
       * </pre>
       *
       * <code>PRIVATE_MESSAGE = 6;</code>
       */
      PRIVATE_MESSAGE(6),
      /**
       * <pre>
       * Requires Text
       * </pre>
       *
       * <code>NOTICE = 7;</code>
       */
      NOTICE(7),
      /**
       * <pre>
       * No message from client to server; requires ChatHistory from server to client
       * </pre>
       *
       * <code>CHAT_HISTORY = 8;</code>
       */
      CHAT_HISTORY(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * DO NOT USE. Must start at 0, but 0 seems to get lost somewhere along the way. Bug in Protobuf?
       * </pre>
       *
       * <code>FAKE = 0;</code>
       */
      public static final int FAKE_VALUE = 0;
      /**
       * <pre>
       * Requires Credentials message
       * </pre>
       *
       * <code>REGISTER = 1;</code>
       */
      public static final int REGISTER_VALUE = 1;
      /**
       * <pre>
       * Requires Credentials message
       * </pre>
       *
       * <code>LOGIN = 2;</code>
       */
      public static final int LOGIN_VALUE = 2;
      /**
       * <pre>
       * No associated message
       * </pre>
       *
       * <code>LOGOUT = 3;</code>
       */
      public static final int LOGOUT_VALUE = 3;
      /**
       * <pre>
       * No associated message
       * </pre>
       *
       * <code>DELETE_ACCOUNT = 4;</code>
       */
      public static final int DELETE_ACCOUNT_VALUE = 4;
      /**
       * <pre>
       * Requires PublicMessage
       * </pre>
       *
       * <code>PUBLIC_MESSAGE = 5;</code>
       */
      public static final int PUBLIC_MESSAGE_VALUE = 5;
      /**
       * <pre>
       * Requires PrivateMessage
       * </pre>
       *
       * <code>PRIVATE_MESSAGE = 6;</code>
       */
      public static final int PRIVATE_MESSAGE_VALUE = 6;
      /**
       * <pre>
       * Requires Text
       * </pre>
       *
       * <code>NOTICE = 7;</code>
       */
      public static final int NOTICE_VALUE = 7;
      /**
       * <pre>
       * No message from client to server; requires ChatHistory from server to client
       * </pre>
       *
       * <code>CHAT_HISTORY = 8;</code>
       */
      public static final int CHAT_HISTORY_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return FAKE;
          case 1: return REGISTER;
          case 2: return LOGIN;
          case 3: return LOGOUT;
          case 4: return DELETE_ACCOUNT;
          case 5: return PUBLIC_MESSAGE;
          case 6: return PRIVATE_MESSAGE;
          case 7: return NOTICE;
          case 8: return CHAT_HISTORY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dylanlaufenberg.cs300.proto.Message.MessageType)
    }

    public interface CredentialsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dylanlaufenberg.cs300.proto.Message.Credentials)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
       * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
       * </pre>
       *
       * <code>string user_name = 1;</code>
       */
      java.lang.String getUserName();
      /**
       * <pre>
       * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
       * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
       * </pre>
       *
       * <code>string user_name = 1;</code>
       */
      com.google.protobuf.ByteString
          getUserNameBytes();

      /**
       * <code>string password = 2;</code>
       */
      java.lang.String getPassword();
      /**
       * <code>string password = 2;</code>
       */
      com.google.protobuf.ByteString
          getPasswordBytes();

      /**
       * <pre>
       * Will be true on successful login, false otherwise.
       * </pre>
       *
       * <code>bool logged_in = 3;</code>
       */
      boolean getLoggedIn();
    }
    /**
     * Protobuf type {@code dylanlaufenberg.cs300.proto.Message.Credentials}
     */
    public  static final class Credentials extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dylanlaufenberg.cs300.proto.Message.Credentials)
        CredentialsOrBuilder {
      // Use Credentials.newBuilder() to construct.
      private Credentials(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Credentials() {
        userName_ = "";
        password_ = "";
        loggedIn_ = false;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Credentials(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                userName_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                password_ = s;
                break;
              }
              case 24: {

                loggedIn_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.class, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder.class);
      }

      public static final int USER_NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object userName_;
      /**
       * <pre>
       * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
       * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
       * </pre>
       *
       * <code>string user_name = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
       * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
       * </pre>
       *
       * <code>string user_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PASSWORD_FIELD_NUMBER = 2;
      private volatile java.lang.Object password_;
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LOGGED_IN_FIELD_NUMBER = 3;
      private boolean loggedIn_;
      /**
       * <pre>
       * Will be true on successful login, false otherwise.
       * </pre>
       *
       * <code>bool logged_in = 3;</code>
       */
      public boolean getLoggedIn() {
        return loggedIn_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getUserNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
        }
        if (!getPasswordBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
        }
        if (loggedIn_ != false) {
          output.writeBool(3, loggedIn_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUserNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
        }
        if (!getPasswordBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
        }
        if (loggedIn_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, loggedIn_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials)) {
          return super.equals(obj);
        }
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials other = (com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials) obj;

        boolean result = true;
        result = result && getUserName()
            .equals(other.getUserName());
        result = result && getPassword()
            .equals(other.getPassword());
        result = result && (getLoggedIn()
            == other.getLoggedIn());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (37 * hash) + LOGGED_IN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLoggedIn());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dylanlaufenberg.cs300.proto.Message.Credentials}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dylanlaufenberg.cs300.proto.Message.Credentials)
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.class, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder.class);
        }

        // Construct using com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          userName_ = "";

          password_ = "";

          loggedIn_ = false;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor;
        }

        public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getDefaultInstanceForType() {
          return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.getDefaultInstance();
        }

        public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials build() {
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials buildPartial() {
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials result = new com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials(this);
          result.userName_ = userName_;
          result.password_ = password_;
          result.loggedIn_ = loggedIn_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials) {
            return mergeFrom((com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials other) {
          if (other == com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.getDefaultInstance()) return this;
          if (!other.getUserName().isEmpty()) {
            userName_ = other.userName_;
            onChanged();
          }
          if (!other.getPassword().isEmpty()) {
            password_ = other.password_;
            onChanged();
          }
          if (other.getLoggedIn() != false) {
            setLoggedIn(other.getLoggedIn());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object userName_ = "";
        /**
         * <pre>
         * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
         * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
         * </pre>
         *
         * <code>string user_name = 1;</code>
         */
        public java.lang.String getUserName() {
          java.lang.Object ref = userName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
         * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
         * </pre>
         *
         * <code>string user_name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUserNameBytes() {
          java.lang.Object ref = userName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
         * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
         * </pre>
         *
         * <code>string user_name = 1;</code>
         */
        public Builder setUserName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          userName_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
         * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
         * </pre>
         *
         * <code>string user_name = 1;</code>
         */
        public Builder clearUserName() {
          
          userName_ = getDefaultInstance().getUserName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Client to server: requires user_name and password. logged_in will be ignored and should be omitted.
         * Server to client: requires logged_in. user_name and password will be ignored and should be omitted.
         * </pre>
         *
         * <code>string user_name = 1;</code>
         */
        public Builder setUserNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          userName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object password_ = "";
        /**
         * <code>string password = 2;</code>
         */
        public java.lang.String getPassword() {
          java.lang.Object ref = password_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            password_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string password = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPasswordBytes() {
          java.lang.Object ref = password_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            password_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string password = 2;</code>
         */
        public Builder setPassword(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          password_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string password = 2;</code>
         */
        public Builder clearPassword() {
          
          password_ = getDefaultInstance().getPassword();
          onChanged();
          return this;
        }
        /**
         * <code>string password = 2;</code>
         */
        public Builder setPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          password_ = value;
          onChanged();
          return this;
        }

        private boolean loggedIn_ ;
        /**
         * <pre>
         * Will be true on successful login, false otherwise.
         * </pre>
         *
         * <code>bool logged_in = 3;</code>
         */
        public boolean getLoggedIn() {
          return loggedIn_;
        }
        /**
         * <pre>
         * Will be true on successful login, false otherwise.
         * </pre>
         *
         * <code>bool logged_in = 3;</code>
         */
        public Builder setLoggedIn(boolean value) {
          
          loggedIn_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Will be true on successful login, false otherwise.
         * </pre>
         *
         * <code>bool logged_in = 3;</code>
         */
        public Builder clearLoggedIn() {
          
          loggedIn_ = false;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:dylanlaufenberg.cs300.proto.Message.Credentials)
      }

      // @@protoc_insertion_point(class_scope:dylanlaufenberg.cs300.proto.Message.Credentials)
      private static final com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials();
      }

      public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Credentials>
          PARSER = new com.google.protobuf.AbstractParser<Credentials>() {
        public Credentials parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Credentials(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Credentials> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Credentials> getParserForType() {
        return PARSER;
      }

      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
     */
    public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType getMessageType() {
      com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType result = com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.valueOf(messageType_);
      return result == null ? com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.UNRECOGNIZED : result;
    }

    public static final int CREDENTIAL_DATA_FIELD_NUMBER = 2;
    private com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials credentialData_;
    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    public boolean hasCredentialData() {
      return credentialData_ != null;
    }
    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getCredentialData() {
      return credentialData_ == null ? com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.getDefaultInstance() : credentialData_;
    }
    /**
     * <pre>
     *    PublicMessage public_message_data = 3;
     *    PrivateMessage private_message_data = 4;
     *    ChatHistory chat_history_data = 5;
     * </pre>
     *
     * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
     */
    public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder getCredentialDataOrBuilder() {
      return getCredentialData();
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 3;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object recipient_;
    /**
     * <code>string recipient = 4;</code>
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      }
    }
    /**
     * <code>string recipient = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 5;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.FAKE.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (credentialData_ != null) {
        output.writeMessage(2, getCredentialData());
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sender_);
      }
      if (!getRecipientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recipient_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.FAKE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (credentialData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCredentialData());
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sender_);
      }
      if (!getRecipientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recipient_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message)) {
        return super.equals(obj);
      }
      com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message other = (com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message) obj;

      boolean result = true;
      result = result && messageType_ == other.messageType_;
      result = result && (hasCredentialData() == other.hasCredentialData());
      if (hasCredentialData()) {
        result = result && getCredentialData()
            .equals(other.getCredentialData());
      }
      result = result && getSender()
          .equals(other.getSender());
      result = result && getRecipient()
          .equals(other.getRecipient());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (hasCredentialData()) {
        hash = (37 * hash) + CREDENTIAL_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getCredentialData().hashCode();
      }
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipient().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A valid NetMessage consists of a message_type field and possibly one, corresponding sub-message as indicated
     * in the MessageType definition comments. If a sub-message is required, it should be populated as indicated
     * in the definition for that message type.
     * Because of the compatibility limitations on required fields, the required keyword is not used. Instead,
     * requirements are expected to be enforced by the applications on either end. It is expected that any extra
     * data sent (e.g. a PrivateMessage with message_type = 0) will be ignored and, most likely, not even detected.
     * </pre>
     *
     * Protobuf type {@code dylanlaufenberg.cs300.proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dylanlaufenberg.cs300.proto.Message)
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.class, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Builder.class);
      }

      // Construct using com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        if (credentialDataBuilder_ == null) {
          credentialData_ = null;
        } else {
          credentialData_ = null;
          credentialDataBuilder_ = null;
        }
        sender_ = "";

        recipient_ = "";

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.internal_static_dylanlaufenberg_cs300_proto_Message_descriptor;
      }

      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message getDefaultInstanceForType() {
        return com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.getDefaultInstance();
      }

      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message build() {
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message buildPartial() {
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message result = new com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message(this);
        result.messageType_ = messageType_;
        if (credentialDataBuilder_ == null) {
          result.credentialData_ = credentialData_;
        } else {
          result.credentialData_ = credentialDataBuilder_.build();
        }
        result.sender_ = sender_;
        result.recipient_ = recipient_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message) {
          return mergeFrom((com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message other) {
        if (other == com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.hasCredentialData()) {
          mergeCredentialData(other.getCredentialData());
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getRecipient().isEmpty()) {
          recipient_ = other.recipient_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
       */
      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType getMessageType() {
        com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType result = com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.valueOf(messageType_);
        return result == null ? com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
       */
      public Builder setMessageType(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dylanlaufenberg.cs300.proto.Message.MessageType message_type = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials credentialData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder> credentialDataBuilder_;
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public boolean hasCredentialData() {
        return credentialDataBuilder_ != null || credentialData_ != null;
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials getCredentialData() {
        if (credentialDataBuilder_ == null) {
          return credentialData_ == null ? com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.getDefaultInstance() : credentialData_;
        } else {
          return credentialDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public Builder setCredentialData(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials value) {
        if (credentialDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          credentialData_ = value;
          onChanged();
        } else {
          credentialDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public Builder setCredentialData(
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder builderForValue) {
        if (credentialDataBuilder_ == null) {
          credentialData_ = builderForValue.build();
          onChanged();
        } else {
          credentialDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public Builder mergeCredentialData(com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials value) {
        if (credentialDataBuilder_ == null) {
          if (credentialData_ != null) {
            credentialData_ =
              com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.newBuilder(credentialData_).mergeFrom(value).buildPartial();
          } else {
            credentialData_ = value;
          }
          onChanged();
        } else {
          credentialDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public Builder clearCredentialData() {
        if (credentialDataBuilder_ == null) {
          credentialData_ = null;
          onChanged();
        } else {
          credentialData_ = null;
          credentialDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder getCredentialDataBuilder() {
        
        onChanged();
        return getCredentialDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder getCredentialDataOrBuilder() {
        if (credentialDataBuilder_ != null) {
          return credentialDataBuilder_.getMessageOrBuilder();
        } else {
          return credentialData_ == null ?
              com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.getDefaultInstance() : credentialData_;
        }
      }
      /**
       * <pre>
       *    PublicMessage public_message_data = 3;
       *    PrivateMessage private_message_data = 4;
       *    ChatHistory chat_history_data = 5;
       * </pre>
       *
       * <code>.dylanlaufenberg.cs300.proto.Message.Credentials credential_data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder> 
          getCredentialDataFieldBuilder() {
        if (credentialDataBuilder_ == null) {
          credentialDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.Credentials.Builder, com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message.CredentialsOrBuilder>(
                  getCredentialData(),
                  getParentForChildren(),
                  isClean());
          credentialData_ = null;
        }
        return credentialDataBuilder_;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 3;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 3;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 3;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 3;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <code>string recipient = 4;</code>
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string recipient = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string recipient = 4;</code>
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 4;</code>
       */
      public Builder clearRecipient() {
        
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <code>string recipient = 4;</code>
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recipient_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 5;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 5;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:dylanlaufenberg.cs300.proto.Message)
    }

    // @@protoc_insertion_point(class_scope:dylanlaufenberg.cs300.proto.Message)
    private static final com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message();
    }

    public static com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.dylanlaufenberg.portlandstate.cs300.proto.NetMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dylanlaufenberg_cs300_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dylanlaufenberg_cs300_proto_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021net_message.proto\022\033dylanlaufenberg.cs3" +
      "00.proto\"\261\003\n\007Message\022F\n\014message_type\030\001 \001" +
      "(\01620.dylanlaufenberg.cs300.proto.Message" +
      ".MessageType\022I\n\017credential_data\030\002 \001(\01320." +
      "dylanlaufenberg.cs300.proto.Message.Cred" +
      "entials\022\016\n\006sender\030\003 \001(\t\022\021\n\trecipient\030\004 \001" +
      "(\t\022\017\n\007message\030\005 \001(\t\032E\n\013Credentials\022\021\n\tus" +
      "er_name\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\tlogge" +
      "d_in\030\003 \001(\010\"\227\001\n\013MessageType\022\010\n\004FAKE\020\000\022\014\n\010" +
      "REGISTER\020\001\022\t\n\005LOGIN\020\002\022\n\n\006LOGOUT\020\003\022\022\n\016DEL",
      "ETE_ACCOUNT\020\004\022\022\n\016PUBLIC_MESSAGE\020\005\022\023\n\017PRI" +
      "VATE_MESSAGE\020\006\022\n\n\006NOTICE\020\007\022\020\n\014CHAT_HISTO" +
      "RY\020\010B;\n-com.dylanlaufenberg.portlandstat" +
      "e.cs300.protoB\nNetMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dylanlaufenberg_cs300_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dylanlaufenberg_cs300_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dylanlaufenberg_cs300_proto_Message_descriptor,
        new java.lang.String[] { "MessageType", "CredentialData", "Sender", "Recipient", "Message", });
    internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor =
      internal_static_dylanlaufenberg_cs300_proto_Message_descriptor.getNestedTypes().get(0);
    internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dylanlaufenberg_cs300_proto_Message_Credentials_descriptor,
        new java.lang.String[] { "UserName", "Password", "LoggedIn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
